// BLUEPRINT LIBRARY
// Ready-made topologies. Each one is a starting point, not an answer — most of
// them are deliberately imperfect so the Doctor has something to teach you.

const N = (id, type, x, y, label, cfg) => ({ id, type, x, y, label, cfg: cfg || {} });
const E = (from, to, kind, ratio) => ({ from, to, kind: kind || 'default', weight: 1, ratio: ratio ?? 1 });

const WL = (o = {}) => ({
  rps: 2000, pattern: 'steady', readPct: 90, payloadKB: 20, timeoutMs: 3000,
  sloSuccessPct: 99, sloP99Ms: 400, budgetUsd: 0, ...o,
});

export const BLUEPRINTS = [
  // ------------------------------------------------------------- beginner
  {
    id: 'naive', name: 'The Naive Design', level: 'Beginner', chapter: '01_from_zero_computers_networks_web.md',
    brief: 'One web server, one database, no cache, no balancer. Every system starts here. Run it, break it, then fix it one component at a time.',
    workload: WL({ rps: 800, sloP99Ms: 300 }),
    nodes: [
      N('c', 'client', 60, 220, 'Users'),
      N('w', 'web_server', 300, 220, 'Web Server', { replicas: 1, threads: 64, cpuMs: 12 }),
      N('db', 'pg_primary', 560, 220, 'PostgreSQL', { maxConns: 100, multiAz: false }),
    ],
    edges: [E('c', 'w'), E('w', 'db')],
  },
  {
    id: 'crud', name: 'Standard CRUD API', level: 'Beginner', chapter: '15_apis_and_protocols.md',
    brief: 'Load balancer, stateless app tier, managed database. The default shape of most business software.',
    workload: WL({ rps: 3000, sloP99Ms: 250 }),
    nodes: [
      N('c', 'client', 60, 240, 'Users'),
      N('lb', 'lb_l7', 260, 240, 'Ingress'),
      N('app', 'app_server', 470, 240, 'API', { replicas: 4, threads: 100, cpuMs: 6 }),
      N('db', 'pg_primary', 700, 240, 'PostgreSQL'),
    ],
    edges: [E('c', 'lb'), E('lb', 'app'), E('app', 'db')],
  },
  {
    id: 'static_site', name: 'Static Site + CDN', level: 'Beginner', chapter: '11_caching_cdn_and_edge.md',
    brief: 'Almost all traffic is absorbed at the edge. Compare origin load with the CDN hit ratio at 90% versus 0%.',
    workload: WL({ rps: 20000, readPct: 100, payloadKB: 350, sloP99Ms: 200 }),
    nodes: [
      N('c', 'client', 60, 240, 'Users'),
      N('cdn', 'cdn', 250, 240, 'CDN'),
      N('lb', 'lb_l7', 460, 240, 'Origin LB'),
      N('web', 'web_server', 660, 240, 'Origin', { replicas: 6 }),
      N('s3', 'object_store', 880, 240, 'Assets'),
    ],
    edges: [E('c', 'cdn'), E('cdn', 'lb'), E('lb', 'web'), E('web', 's3')],
  },

  // --------------------------------------------------------- intermediate
  {
    id: 'url_shortener', name: 'URL Shortener', level: 'Intermediate', chapter: '24_case_studies_part1.md',
    brief: 'Extremely read-heavy, tiny payloads, hard latency target. The canonical cache-and-KV problem.',
    workload: WL({ rps: 40000, readPct: 99, payloadKB: 1, sloP99Ms: 60, budgetUsd: 6000 }),
    nodes: [
      N('c', 'client', 60, 260, 'Users'),
      N('cdn', 'cdn', 220, 260, 'CDN', { hitRatio: 55 }),
      N('gw', 'api_gateway', 400, 260, 'Gateway'),
      N('app', 'app_server', 590, 260, 'Redirect Svc', { replicas: 6, threads: 200, cpuMs: 1.2 }),
      N('cache', 'redis_cluster', 790, 180, 'Redis', { shards: 3, hitRatio: 97 }),
      N('kv', 'kv_store', 1000, 260, 'DynamoDB'),
      N('id', 'app_server', 590, 400, 'ID Generator', { replicas: 2, cpuMs: 0.4 }),
    ],
    edges: [E('c', 'cdn'), E('cdn', 'gw'), E('gw', 'app'), E('app', 'cache'), E('cache', 'kv'), E('gw', 'id', 'write')],
  },
  {
    id: 'social_feed', name: 'Social Feed (Timeline)', level: 'Intermediate', chapter: '25_case_studies_part2.md',
    brief: 'Fan-out on write via a queue, fan-out on read via cache. Watch what happens when the celebrity problem hits.',
    workload: WL({ rps: 25000, readPct: 92, payloadKB: 45, sloP99Ms: 350, budgetUsd: 25000 }),
    nodes: [
      N('c', 'client', 60, 300, 'Users'),
      N('gw', 'api_gateway', 230, 300, 'Gateway'),
      N('feed', 'k8s_deploy', 430, 220, 'Feed Service', { minPods: 6, maxPods: 60, cpuMs: 8 }),
      N('cache', 'redis_cluster', 650, 150, 'Timeline Cache', { shards: 6, hitRatio: 93, workingSetGB: 300, memPerShardGB: 52 }),
      N('db', 'sql_sharded', 900, 220, 'Posts (sharded)', { shards: 8 }),
      N('post', 'app_server', 430, 400, 'Write Service', { replicas: 4, cpuMs: 5 }),
      N('kafka', 'kafka', 650, 400, 'fanout-topic', { partitions: 24, brokers: 5 }),
      N('worker', 'worker_pool', 880, 400, 'Fan-out Workers', { replicas: 12, jobMs: 40 }),
    ],
    edges: [E('c', 'gw'), E('gw', 'feed', 'read'), E('gw', 'post', 'write'), E('feed', 'cache'), E('cache', 'db'), E('post', 'db'), E('post', 'kafka'), E('kafka', 'worker'), E('worker', 'cache')],
  },
  {
    id: 'chat', name: 'Real-Time Chat', level: 'Intermediate', chapter: '25_case_studies_part2.md',
    brief: 'WebSockets scale on concurrent connections, not RPS. Presence and history are separate problems.',
    workload: WL({ rps: 12000, readPct: 60, payloadKB: 2, sloP99Ms: 200, budgetUsd: 15000 }),
    nodes: [
      N('c', 'client', 60, 280, 'Clients'),
      N('lb', 'lb_l4', 230, 280, 'TCP LB'),
      N('ws', 'websocket_gw', 420, 280, 'WS Gateway', { replicas: 8, connPerNode: 60000 }),
      N('chat', 'app_server', 640, 200, 'Chat Service', { replicas: 8, cpuMs: 3 }),
      N('presence', 'redis_cluster', 640, 380, 'Presence', { shards: 3, hitRatio: 99 }),
      N('kafka', 'kafka', 860, 200, 'messages', { partitions: 32 }),
      N('store', 'wide_column', 1080, 200, 'Message History', { nodes: 9 }),
    ],
    edges: [E('c', 'lb'), E('lb', 'ws'), E('ws', 'chat'), E('ws', 'presence'), E('chat', 'kafka'), E('kafka', 'store')],
  },
  {
    id: 'ecommerce', name: 'E-Commerce Storefront', level: 'Intermediate', chapter: '24_case_studies_part1.md',
    brief: 'Browse is read-heavy and cacheable; checkout is write-heavy, transactional and touches a payment provider you do not control.',
    workload: WL({ rps: 9000, readPct: 88, payloadKB: 120, sloP99Ms: 450, budgetUsd: 20000 }),
    nodes: [
      N('c', 'client', 50, 300, 'Shoppers'),
      N('cdn', 'cdn', 200, 300, 'CDN'),
      N('waf', 'waf', 350, 300, 'WAF'),
      N('gw', 'api_gateway', 500, 300, 'Gateway'),
      N('catalog', 'k8s_deploy', 700, 180, 'Catalog', { minPods: 6, maxPods: 40, cpuMs: 7 }),
      N('cache', 'redis', 900, 110, 'Catalog Cache', { hitRatio: 94, memGB: 52, workingSetGB: 60 }),
      N('search', 'search', 900, 250, 'Search', { nodes: 4, shards: 8 }),
      N('cart', 'app_server', 700, 330, 'Cart', { replicas: 5, cpuMs: 4 }),
      N('order', 'app_server', 700, 470, 'Checkout', { replicas: 5, cpuMs: 12, timeoutMs: 2000 }),
      N('db', 'pg_primary', 1120, 330, 'Orders DB', { maxConns: 200 }),
      N('rr', 'pg_replica', 1120, 190, 'Read Replicas', { replicas: 3 }),
      N('mq', 'queue', 900, 470, 'order-events'),
      N('pay', 'payment_gw', 1120, 470, 'Stripe'),
      N('mail', 'notification', 1120, 580, 'Email/SMS', { rateLimit: 4000 }),
      N('w', 'worker_pool', 1120, 640, 'Order Workers', { replicas: 40, concurrency: 16, jobMs: 120 }),
    ],
    edges: [
      E('c', 'cdn'), E('cdn', 'waf'), E('waf', 'gw'),
      E('gw', 'catalog', 'read'), E('gw', 'cart'), E('gw', 'order', 'write'),
      E('catalog', 'cache'), E('cache', 'rr'), E('catalog', 'search', 'default', 0.3),
      E('cart', 'db'), E('order', 'db'), E('order', 'pay', 'default', 0.4), E('order', 'mq'),
      E('mq', 'w'), E('w', 'mail', 'default', 0.5),
    ],
  },
  {
    id: 'video', name: 'Video Upload & Streaming', level: 'Intermediate', chapter: '25_case_studies_part2.md',
    brief: 'Upload is a slow write pipeline; playback is a cheap CDN read. Never let them share a code path.',
    workload: WL({ rps: 15000, readPct: 99.5, payloadKB: 800, sloP99Ms: 600, budgetUsd: 60000 }),
    nodes: [
      N('c', 'client', 60, 300, 'Viewers'),
      N('cdn', 'cdn', 230, 220, 'CDN', { hitRatio: 96, egressGBmo: 0.085 }),
      N('gw', 'api_gateway', 230, 400, 'Upload API'),
      N('meta', 'app_server', 430, 220, 'Metadata Svc', { replicas: 6, cpuMs: 4 }),
      N('cache', 'redis', 640, 150, 'Metadata Cache', { hitRatio: 95 }),
      N('db', 'kv_store', 860, 220, 'Video Metadata'),
      N('up', 'app_server', 430, 400, 'Upload Svc', { replicas: 8, threads: 200, cpuMs: 20 }),
      N('s3', 'object_store', 640, 470, 'Raw Storage', { dataTB: 900 }),
      N('mq', 'queue', 640, 380, 'transcode-jobs'),
      N('tr', 'worker_pool', 860, 380, 'Transcoders', { replicas: 400, concurrency: 6, jobMs: 30000 }),
      N('out', 'object_store', 1080, 380, 'HLS Segments', { dataTB: 2500 }),
    ],
    edges: [E('c', 'cdn', 'read'), E('cdn', 'meta'), E('meta', 'cache'), E('cache', 'db'), E('c', 'gw', 'write'), E('gw', 'up'), E('up', 's3'), E('up', 'mq'), E('mq', 'tr'), E('tr', 'out'), E('cdn', 'out')],
  },
  {
    id: 'notification', name: 'Notification Service', level: 'Intermediate', chapter: '25_case_studies_part2.md',
    brief: 'Fan-out to slow, rate-limited, unreliable third parties. Everything after the queue is someone else\'s SLA — including the bill, which here dwarfs the infrastructure.',
    workload: WL({ rps: 800, readPct: 10, sloP99Ms: 300, budgetUsd: 500000 }),
    nodes: [
      N('c', 'client', 60, 280, 'Services'),
      N('gw', 'api_gateway', 240, 280, 'Notify API'),
      N('svc', 'app_server', 430, 280, 'Dispatcher', { replicas: 4, cpuMs: 3 }),
      N('mq', 'queue', 620, 280, 'notify-queue', { dlq: true }),
      N('w', 'worker_pool', 810, 280, 'Senders', { replicas: 50, concurrency: 16, jobMs: 400 }),
      N('cb', 'circuit_breaker', 1000, 200, 'Breaker'),
      N('email', 'notification', 1180, 140, 'Email', { rateLimit: 3000, costPer1k: 0.1 }),
      N('sms', 'notification', 1180, 260, 'SMS', { rateLimit: 1500, costPer1k: 0.6 }),
      N('dlq', 'dlq', 1000, 380, 'Dead Letters'),
    ],
    edges: [E('c', 'gw'), E('gw', 'svc'), E('svc', 'mq'), E('mq', 'w'), E('w', 'cb'), E('cb', 'email', 'default', 0.8), E('cb', 'sms', 'default', 0.2), E('w', 'dlq', 'default', 0.02)],
  },
  {
    id: 'ratelimiter', name: 'Distributed Rate Limiter', level: 'Intermediate', chapter: '23_building_blocks_and_algorithms.md',
    brief: 'Every request pays a shared-counter round trip. Compare distributed accuracy against local speed.',
    workload: WL({ rps: 60000, readPct: 95, sloP99Ms: 50, budgetUsd: 5000 }),
    nodes: [
      N('c', 'client', 60, 260, 'Clients'),
      N('gw', 'api_gateway', 240, 260, 'Gateway', { rateLimit: false }),
      N('rl', 'rate_limiter', 430, 260, 'Token Bucket', { rate: 70000, burst: 140000 }),
      N('redis', 'redis_cluster', 430, 400, 'Counter Store', { shards: 4, hitRatio: 100 }),
      N('app', 'k8s_deploy', 640, 260, 'API', { minPods: 8, maxPods: 80, cpuMs: 3 }),
      N('db', 'kv_store', 860, 260, 'Data'),
    ],
    edges: [E('c', 'gw'), E('gw', 'rl'), E('rl', 'redis'), E('rl', 'app'), E('app', 'db')],
  },

  // -------------------------------------------------------------- advanced
  {
    id: 'rideshare', name: 'Ride-Hailing Dispatch', level: 'Advanced', chapter: '25_case_studies_part2.md',
    brief: 'Geospatial writes at very high frequency, matching under a lock, and a payment leg. Three different scaling problems in one system.',
    workload: WL({ rps: 45000, readPct: 55, sloP99Ms: 400, budgetUsd: 60000 }),
    nodes: [
      N('c', 'client', 50, 320, 'Riders + Drivers'),
      N('lb', 'lb_l7', 200, 320, 'Edge LB'),
      N('gw', 'api_gateway', 360, 320, 'Gateway'),
      N('loc', 'k8s_deploy', 550, 180, 'Location Ingest', { minPods: 10, maxPods: 120, cpuMs: 1.5 }),
      N('geo', 'redis_cluster', 780, 120, 'Geo Index', { shards: 8, hitRatio: 99 }),
      N('match', 'app_server', 550, 330, 'Matching', { replicas: 24, threads: 120, cpuMs: 25, callMode: 'parallel' }),
      N('lock', 'dist_lock', 780, 330, 'Driver Lock', { keys: 50000, holdMs: 8 }),
      N('trip', 'app_server', 550, 480, 'Trip Service', { replicas: 6, cpuMs: 8 }),
      N('db', 'sql_sharded', 1000, 480, 'Trips DB', { shards: 16 }),
      N('kafka', 'kafka', 780, 480, 'trip-events', { partitions: 48, brokers: 6 }),
      N('cb', 'circuit_breaker', 1000, 610, 'Pay Breaker'),
      N('pay', 'payment_gw', 1180, 610, 'Payments', { rateLimit: 3000 }),
      N('w', 'worker_pool', 1000, 380, 'Event Workers', { replicas: 60, concurrency: 16, jobMs: 30 }),
    ],
    edges: [E('c', 'lb'), E('lb', 'gw'), E('gw', 'loc', 'write'), E('loc', 'geo'), E('gw', 'match', 'read'), E('match', 'geo'), E('match', 'lock'), E('gw', 'trip'), E('trip', 'db'), E('trip', 'kafka'), E('kafka', 'w'), E('w', 'cb', 'default', 0.05), E('cb', 'pay')],
  },
  {
    id: 'flash_sale', name: 'Flash Sale / Ticketing', level: 'Advanced', chapter: '24_case_studies_part1.md',
    brief: 'A hundred thousand people trying to buy ten thousand items in one second. Oversell is unacceptable, so something has to serialise.',
    workload: WL({ rps: 5000, pattern: 'flashsale', spikeMult: 30, readPct: 70, sloP99Ms: 800, sloSuccessPct: 95, budgetUsd: 30000 }),
    nodes: [
      N('c', 'client', 50, 300, 'Buyers'),
      N('cdn', 'cdn', 190, 300, 'CDN', { hitRatio: 90 }),
      N('waf', 'waf', 330, 300, 'WAF'),
      N('rl', 'rate_limiter', 470, 300, 'Admission', { rate: 25000, burst: 60000 }),
      N('gw', 'api_gateway', 620, 300, 'Gateway'),
      N('app', 'k8s_deploy', 790, 200, 'Sale API', { minPods: 20, maxPods: 250, cpuMs: 4 }),
      N('inv', 'redis_cluster', 1000, 130, 'Inventory Counter', { shards: 6, hitRatio: 100 }),
      N('mq', 'queue', 1000, 260, 'order-intake', { maxDepth: 5000000 }),
      N('w', 'worker_pool', 1200, 260, 'Order Workers', { replicas: 30, jobMs: 60 }),
      N('db', 'pg_primary', 1400, 260, 'Orders', { maxConns: 400 }),
      N('pool', 'pgbouncer', 1300, 380, 'PgBouncer'),
    ],
    edges: [E('c', 'cdn'), E('cdn', 'waf'), E('waf', 'rl'), E('rl', 'gw'), E('gw', 'app'), E('app', 'inv'), E('app', 'mq'), E('mq', 'w'), E('w', 'pool'), E('pool', 'db')],
  },
  {
    id: 'microservices', name: 'Microservices with Mesh', level: 'Advanced', chapter: '16_microservices_and_service_architecture.md',
    brief: 'Six services, a mesh, and a deep synchronous chain. Count the hops, then compute the availability.',
    workload: WL({ rps: 8000, readPct: 85, sloP99Ms: 500, budgetUsd: 30000 }),
    nodes: [
      N('c', 'client', 50, 300, 'Users'),
      N('gw', 'api_gateway', 210, 300, 'Gateway'),
      N('bff', 'app_server', 380, 300, 'BFF', { replicas: 6, cpuMs: 3, callMode: 'parallel' }),
      N('mesh', 'service_mesh', 550, 300, 'Mesh'),
      N('user', 'app_server', 730, 140, 'User Svc', { replicas: 4, cpuMs: 4 }),
      N('prod', 'app_server', 730, 260, 'Product Svc', { replicas: 4, cpuMs: 5 }),
      N('rec', 'app_server', 730, 380, 'Recs Svc', { replicas: 3, cpuMs: 30 }),
      N('inv', 'app_server', 730, 500, 'Inventory Svc', { replicas: 3, cpuMs: 6 }),
      N('udb', 'pg_primary', 960, 140, 'User DB'),
      N('pdb', 'document_db', 960, 260, 'Product DB'),
      N('vdb', 'vector_db', 960, 380, 'Vectors'),
      N('idb', 'kv_store', 960, 500, 'Inventory KV'),
    ],
    edges: [E('c', 'gw'), E('gw', 'bff'), E('bff', 'mesh'), E('mesh', 'user'), E('mesh', 'prod'), E('mesh', 'rec'), E('mesh', 'inv'), E('user', 'udb'), E('prod', 'pdb'), E('rec', 'vdb'), E('inv', 'idb')],
  },
  {
    id: 'analytics', name: 'Analytics Pipeline', level: 'Advanced', chapter: '13_big_data_batch_stream_analytics.md',
    brief: 'Ingest everything, process in a stream, serve pre-aggregates. The lambda/kappa split in one picture.',
    workload: WL({ rps: 120000, readPct: 5, payloadKB: 1.5, sloP99Ms: 1000, budgetUsd: 45000 }),
    nodes: [
      N('c', 'client', 50, 300, 'Event Producers'),
      N('gw', 'lb_l7', 210, 300, 'Collector LB', { capacity: 500000 }),
      N('ing', 'k8s_deploy', 380, 300, 'Ingest', { minPods: 20, maxPods: 200, cpuMs: 0.6 }),
      N('kafka', 'kafka', 580, 300, 'events', { partitions: 96, brokers: 9, mbPerBrokerS: 200 }),
      N('flink', 'stream_processor', 780, 220, 'Flink Jobs', { parallelism: 128, perEventMs: 0.2 }),
      N('lake', 'data_lake', 780, 400, 'Data Lake', { dataTB: 900, concurrency: 400, scanMs: 40 }),
      N('ch', 'olap', 1010, 220, 'ClickHouse', { nodes: 8, concurrency: 200, queryMs: 100 }),
      N('an', 'client', 1010, 430, 'Analysts', { sharePct: 1, payloadKB: 200 }),
      N('api', 'app_server', 1210, 300, 'Query API', { replicas: 6, cpuMs: 5 }),
      N('cache', 'redis', 1210, 430, 'Result Cache', { hitRatio: 80 }),
    ],
    edges: [E('c', 'gw'), E('gw', 'ing'), E('ing', 'kafka'), E('kafka', 'flink'), E('kafka', 'lake', 'default', 0.002), E('flink', 'ch', 'default', 0.01), E('an', 'api'), E('api', 'cache'), E('cache', 'ch')],
  },
  {
    id: 'multiregion', name: 'Multi-Region Active-Active', level: 'Advanced', chapter: '20_deployment_multiregion_dr_cost.md',
    brief: 'Two regions, geo-routed, with a globally consistent database. Every write now costs an ocean crossing.',
    workload: WL({ rps: 20000, readPct: 85, sloP99Ms: 500, budgetUsd: 80000 }),
    nodes: [
      N('c', 'client', 50, 300, 'Global Users'),
      N('dns', 'dns', 200, 300, 'GeoDNS', { geo: true, ttlSec: 60 }),
      N('lb1', 'lb_l7', 380, 180, 'us-east LB'),
      N('lb2', 'lb_l7', 380, 420, 'eu-west LB'),
      N('app1', 'k8s_deploy', 570, 180, 'us-east App', { minPods: 8, maxPods: 60 }),
      N('app2', 'k8s_deploy', 570, 420, 'eu-west App', { minPods: 8, maxPods: 60 }),
      N('cache1', 'redis_cluster', 780, 100, 'us-east Cache', { shards: 4 }),
      N('cache2', 'redis_cluster', 780, 500, 'eu-west Cache', { shards: 4 }),
      N('db', 'newsql', 800, 300, 'Global DB', { nodes: 9, multiRegion: true, regionRttMs: 85 }),
    ],
    edges: [E('c', 'dns'), E('dns', 'lb1', 'default', 1), E('dns', 'lb2', 'default', 1), E('lb1', 'app1'), E('lb2', 'app2'), E('app1', 'cache1'), E('app2', 'cache2'), E('cache1', 'db'), E('cache2', 'db')],
  },
  {
    id: 'stock_exchange', name: 'Order Matching Engine', level: 'Advanced', chapter: '22_landmark_papers_and_architectures.md',
    brief: 'Matching must be strictly ordered, so it runs single-threaded on purpose. Everything else exists to keep that one thread fed.',
    workload: WL({ rps: 80000, readPct: 70, payloadKB: 0.5, sloP99Ms: 20, budgetUsd: 50000 }),
    nodes: [
      N('c', 'client', 50, 300, 'Traders'),
      N('gw', 'lb_l4', 210, 300, 'FIX Gateway', { capacity: 1000000, procMs: 0.15 }),
      N('risk', 'app_server', 380, 300, 'Risk Checks', { replicas: 12, threads: 400, cpuMs: 0.3 }),
      N('seq', 'consensus', 560, 300, 'Sequencer', { nodes: 3, rttMs: 0.3, writeCap: 200000 }),
      N('match', 'app_server', 750, 300, 'Matching Engine', { replicas: 1, threads: 256, cpuMs: 0.008, callMode: 'parallel' }),
      N('kafka', 'kafka', 940, 220, 'trade-log', { partitions: 8, acks: 'all', produceMs: 1 }),
      N('md', 'websocket_gw', 940, 400, 'Market Data', { replicas: 12, pushMs: 0.4 }),
      N('db', 'timeseries', 1140, 220, 'Trade Store', { nodes: 12 }),
    ],
    edges: [E('c', 'gw'), E('gw', 'risk'), E('risk', 'seq'), E('seq', 'match'), E('match', 'kafka'), E('match', 'md'), E('kafka', 'db')],
  },
  {
    id: 'search_engine', name: 'Search & Autocomplete', level: 'Advanced', chapter: '14_search_systems.md',
    brief: 'Scatter-gather across shards means your p99 is the slowest shard, not the average one. Watch the shard count change the tail.',
    workload: WL({ rps: 30000, readPct: 97, sloP99Ms: 200, budgetUsd: 25000 }),
    nodes: [
      N('c', 'client', 50, 280, 'Users'),
      N('cdn', 'cdn', 200, 280, 'Edge', { hitRatio: 45 }),
      N('gw', 'api_gateway', 360, 280, 'Gateway'),
      N('ac', 'app_server', 540, 160, 'Autocomplete', { replicas: 8, cpuMs: 1 }),
      N('trie', 'redis_cluster', 740, 110, 'Prefix Cache', { shards: 4, hitRatio: 96 }),
      N('q', 'app_server', 540, 320, 'Query Service', { replicas: 8, cpuMs: 4, callMode: 'parallel' }),
      N('es', 'search', 760, 300, 'Elasticsearch', { nodes: 8, shards: 24 }),
      N('rank', 'app_server', 760, 450, 'Ranker', { replicas: 6, cpuMs: 18 }),
      N('cache', 'redis', 960, 400, 'Result Cache', { hitRatio: 65 }),
    ],
    edges: [E('c', 'cdn'), E('cdn', 'gw'), E('gw', 'ac'), E('ac', 'trie'), E('gw', 'q'), E('q', 'cache'), E('cache', 'es'), E('q', 'rank')],
  },
  {
    id: 'iot', name: 'IoT Telemetry Ingest', level: 'Advanced', chapter: '13_big_data_batch_stream_analytics.md',
    brief: 'Millions of tiny writes per second from devices that retry aggressively when you go down.',
    workload: WL({ rps: 200000, readPct: 3, payloadKB: 0.3, sloP99Ms: 2000, sloSuccessPct: 99.5, budgetUsd: 35000 }),
    nodes: [
      N('c', 'client', 50, 300, 'Devices'),
      N('lb', 'lb_l4', 200, 300, 'MQTT LB', { capacity: 2000000 }),
      N('br', 'websocket_gw', 370, 300, 'MQTT Brokers', { replicas: 20, connPerNode: 200000, pushMs: 0.5 }),
      N('kafka', 'kafka', 570, 300, 'telemetry', { partitions: 128, brokers: 12, mbPerBrokerS: 250, msgKB: 0.3 }),
      N('flink', 'stream_processor', 780, 220, 'Aggregator', { parallelism: 200, perEventMs: 0.05 }),
      N('tsdb', 'timeseries', 990, 220, 'TSDB', { nodes: 12, cardinality: 20000000 }),
      N('alert', 'app_server', 990, 380, 'Alerting', { replicas: 4, threads: 400, cpuMs: 0.4 }),
      N('cold', 'object_store', 780, 400, 'Cold Archive', { dataTB: 400, tier: 'infrequent' }),
    ],
    edges: [E('c', 'lb'), E('lb', 'br'), E('br', 'kafka'), E('kafka', 'flink'), E('flink', 'tsdb', 'default', 0.02), E('flink', 'alert', 'default', 0.01), E('kafka', 'cold', 'default', 0.001)],
  },

  // ------------------------------------------------------------ AI systems
  {
    id: 'rag', name: 'RAG Question Answering', level: 'AI', chapter: '14_search_systems.md',
    brief: 'Retrieval is cheap and fast; generation is slow and expensive. The cache in front of the LLM is worth more than everything else combined — check the cost tab.',
    workload: WL({ rps: 40, readPct: 98, sloP99Ms: 8000, timeoutMs: 30000, budgetUsd: 150000 }),
    nodes: [
      N('c', 'client', 50, 280, 'Users'),
      N('gw', 'api_gateway', 220, 280, 'Gateway', { limitRps: 800 }),
      N('rl', 'rate_limiter', 390, 280, 'Per-tenant Limit', { rate: 500 }),
      N('svc', 'app_server', 560, 280, 'RAG Service', { replicas: 6, threads: 2000, cpuMs: 6, callMode: 'sequential', timeoutMs: 30000 }),
      N('scache', 'redis', 740, 150, 'Semantic Cache', { hitRatio: 40, getMs: 3 }),
      N('emb', 'embedding_svc', 740, 400, 'Embeddings', { replicas: 3 }),
      N('vec', 'vector_db', 940, 400, 'Vector DB', { vectors: 20000000 }),
      N('llm', 'llm_service', 940, 250, 'LLM', { gpus: 24, outTokens: 250 }),
    ],
    edges: [E('c', 'gw'), E('gw', 'rl'), E('rl', 'svc'), E('svc', 'scache'), E('scache', 'emb'), E('emb', 'vec'), E('scache', 'llm')],
  },
  {
    id: 'agent', name: 'Agentic Tool Pipeline (MCP)', level: 'AI', chapter: '15_apis_and_protocols.md',
    brief: 'Each reasoning step is a full LLM round trip plus a tool call. Multiply everything by the step count and the numbers get frightening fast.',
    workload: WL({ rps: 5, readPct: 90, sloP99Ms: 60000, timeoutMs: 180000, budgetUsd: 120000 }),
    nodes: [
      N('c', 'client', 50, 280, 'Users'),
      N('gw', 'api_gateway', 220, 280, 'Gateway', { timeoutMs: 180000 }),
      N('agent', 'agent_runtime', 400, 280, 'Agent', { replicas: 4, steps: 4, concurrency: 2000 }),
      N('llm', 'llm_service', 620, 160, 'LLM', { gpus: 10, outTokens: 300, inTokens: 3000 }),
      N('mcp', 'mcp_server', 620, 400, 'MCP Tools', { replicas: 4, toolMs: 350, concurrency: 128 }),
      N('cb', 'circuit_breaker', 820, 400, 'Tool Breaker'),
      N('ext', 'third_party', 1010, 400, 'External APIs', { rateLimit: 5000 }),
      N('vec', 'vector_db', 820, 520, 'Memory Store'),
    ],
    edges: [E('c', 'gw'), E('gw', 'agent'), E('agent', 'llm'), E('agent', 'mcp'), E('mcp', 'cb'), E('cb', 'ext'), E('agent', 'vec')],
  },

  // ------------------------------------------------------------ resilience
  {
    id: 'resilient', name: 'Fully Hardened Reference', level: 'Reference', chapter: '03_reliability_availability_performance.md',
    brief: 'Everything the Doctor asks for, in one topology: edge shedding, caching, pooling, queuing, breakers, replicas, observability. Use it as a checklist.',
    workload: WL({ rps: 30000, readPct: 90, sloP99Ms: 300, sloSuccessPct: 99.9, budgetUsd: 45000 }),
    nodes: [
      N('c', 'client', 40, 320, 'Users'),
      N('cdn', 'cdn', 170, 320, 'CDN', { hitRatio: 80, shield: true }),
      N('waf', 'waf', 300, 320, 'WAF'),
      N('rl', 'rate_limiter', 430, 320, 'Rate Limiter', { rate: 45000 }),
      N('gw', 'api_gateway', 560, 320, 'Gateway', { replicas: 4 }),
      N('app', 'k8s_deploy', 710, 240, 'API Pods', { minPods: 10, maxPods: 120, cpuMs: 5, targetCpu: 60 }),
      N('cache', 'redis_cluster', 890, 150, 'Cache', { shards: 6, hitRatio: 95, coalescing: true, workingSetGB: 200, memPerShardGB: 52 }),
      N('pool', 'pgbouncer', 1080, 220, 'PgBouncer', { serverConns: 180 }),
      N('rr', 'pg_replica', 1260, 140, 'Read Replicas', { replicas: 3 }),
      N('db', 'pg_primary', 1260, 280, 'Primary', { maxConns: 400, multiAz: true }),
      N('bh', 'bulkhead', 880, 620, 'Bulkhead', { permits: 400 }),
      N('cb', 'circuit_breaker', 1060, 620, 'Breaker'),
      N('ext', 'third_party', 1240, 620, 'Partner API', { rateLimit: 8000 }),
      N('mq', 'queue', 880, 530, 'async-work'),
      N('w', 'worker_pool', 1060, 530, 'Workers', { replicas: 60, concurrency: 20, jobMs: 80 }),
      N('dlq', 'dlq', 1240, 530, 'DLQ'),
      N('obs', 'observability', 710, 560, 'Telemetry'),
    ],
    edges: [
      E('c', 'cdn'), E('cdn', 'waf'), E('waf', 'rl'), E('rl', 'gw'), E('gw', 'app'),
      E('app', 'cache'), E('cache', 'pool'), E('pool', 'rr', 'read'), E('pool', 'db', 'write'),
      E('app', 'mq', 'write'), E('mq', 'w'), E('w', 'bh'), E('bh', 'cb'), E('cb', 'ext'),
      E('w', 'dlq', 'default', 0.01), E('app', 'obs'),
    ],
  },
];

export function blueprintToGraph(bp) {
  return {
    version: 1,
    name: bp.name,
    workload: { ...bp.workload },
    nodes: bp.nodes.map((n) => ({ ...n, cfg: { ...n.cfg } })),
    edges: bp.edges.map((e, i) => ({ id: 'e' + i, ...e })),
  };
}

export const BLUEPRINT_LEVELS = [...new Set(BLUEPRINTS.map((b) => b.level))];
